nota1 = float(input('Digite a primeira nota'))
nota2 = float(input('Digite a segunda nota'))
nota3 = float(input('Digite a terceira nota'))
me = ((nota1+nota2+nota3)/3)
ma = ((nota1+(nota2 * 2) + (nota3*3)+me)/7)
print ('MA = ',ma)